### ISSUE TITLE
Doing tests

### ISSUE THREAD

**Issue by ktakats** [dhuppenkothen/entrofy#4]
I started an ipython notebook to do some tests, I'd like to put it in the notebook folder, but I can't figure it out how to import entrofy in the notebook using a relative path. Anyone knows how to do it?

**Comment by bmcfee** [comment]
You can do 

```python
import sys
sys.path.append('/path/to/folder')

import entrofy

# Proceed as normal...
```

**Comment by ktakats** [comment]
Thanks.
