### ISSUE TITLE
A better name?

### ISSUE THREAD

**Issue by bmcfee** [dhuppenkothen/entrofy#5]
I figure most potential users of this thing won't have a clue what entropy means.

Can we come up with something a bit more people-friendly?

**Comment by cranmer** [comment]
Ideas:

1) *convergerence* (Conference+convergence = *convergerence )

2) *cohortor* ‎(present infinitive cohortārī, perfect active cohortātus sum); first conjugation, deponent

Meaning: I encourage or exhort

**Comment by cranmer** [comment]
no votes for 'cohortor' ?
I mentioned intent to use this tool in an NSF proposal :+1:
